# Generated by Django 5.0.6 on 2024-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description_one', models.CharField(max_length=200)),
                ('image_one', models.ImageField(upload_to='')),
                ('detail_one', models.TextField()),
                ('price_one', models.IntegerField()),
                ('description_two', models.CharField(max_length=200)),
                ('image_two', models.ImageField(upload_to='')),
                ('detail_two', models.TextField()),
                ('price_two', models.IntegerField()),
                ('description_three', models.CharField(max_length=200)),
                ('image_three', models.ImageField(upload_to='')),
                ('detail_three', models.TextField()),
                ('price_three', models.IntegerField()),
                ('description_four', models.CharField(max_length=200)),
                ('image_four', models.ImageField(upload_to='')),
                ('detail_four', models.TextField()),
                ('price_four', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
