# Generated by Django 5.0.6 on 2024-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitie',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AddField(
            model_name='activitie',
            name='province_image',
            field=models.ImageField(default=1, upload_to='province_images', verbose_name='Imagen de la Provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='description_four',
            field=models.CharField(max_length=200, verbose_name='Titulo de la actividad 4'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='description_one',
            field=models.CharField(max_length=200, verbose_name='Titulo de la actividad 1'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='description_three',
            field=models.CharField(max_length=200, verbose_name='Titulo de la actividad 3'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='description_two',
            field=models.CharField(max_length=200, verbose_name='Titulo de la actividad 2'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='detail_four',
            field=models.TextField(verbose_name='Detalle de la actividad 4'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='detail_one',
            field=models.TextField(verbose_name='Detalle de la actividad 1'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='detail_three',
            field=models.TextField(verbose_name='Detalle de la actividad 3'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='detail_two',
            field=models.TextField(verbose_name='Detalle de la actividad 2'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='image_four',
            field=models.ImageField(upload_to='province_images', verbose_name='Imagen de la actividad 4'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='image_one',
            field=models.ImageField(upload_to='province_images', verbose_name='Imagen de la actividad 1'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='image_three',
            field=models.ImageField(upload_to='province_images', verbose_name='Imagen de la actividad 3'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='image_two',
            field=models.ImageField(upload_to='province_images', verbose_name='Imagen de la actividad 2'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la provincia'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='price_four',
            field=models.IntegerField(verbose_name='Precio de la actividad 4'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='price_one',
            field=models.IntegerField(verbose_name='Precio de la actividad 1'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='price_three',
            field=models.IntegerField(verbose_name='Precio de la actividad 3'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='price_two',
            field=models.IntegerField(verbose_name='Precio de la actividad 2'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
